# 메일 인증
spring:
  mail:
    host: smtp.gmail.com        # SMTP 서버 호스트
    username: 1479242           # SMTP 서버 로그인 아이디
    password: sdhedwxbjmpughqz  # SMTP 서버 로그인 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:crm  # JDBC URL이 매번 랜덤하게 바뀌지 않도록 고정
    sql:
      init:
        # schema.sql 파일의 스크립트를 읽어, 애플리케이션 실행 시 DB에 테이블을 자동으로 생성해줌
        schema-locations: classpath*:db/h2/schema.sql
        #
        data-locations: classpath*:db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug